// This file is automatically generated by generate_decoder.py.
// Do not edit it manually.

module emu.hw.dsp.jit.emission.decoder;

import util.bitop;
import util.number;
import util.log;

struct DspInstruction {
    DspOpcode opcode;
    size_t size;

    union {
        MOVPZ movpz;
		CLRL clrl;
		ADDPAXZ addpaxz;
		MSUB msub;
		LSR16 lsr16;
		MADD madd;
		LSL16 lsl16;
		MSUBC msubc;
		MADDC maddc;
		MSUBX msubx;
		MADDX maddx;
		MULCMV mulcmv;
		MULCAC mulcac;
		MULCMVZ mulcmvz;
		CMPAXH cmpaxh;
		MULC mulc;
		MULXMV mulxmv;
		MULXAC mulxac;
		MULXMVZ mulxmvz;
		TST tst;
		ABS abs;
		MULX mulx;
		MULMV mulmv;
		MULAC mulac;
		MULMVZ mulmvz;
		ASR16 asr16;
		MUL mul;
		SET40 set40;
		SET16 set16;
		SET15 set15;
		CLR15 clr15;
		M0 m0;
		M2 m2;
		TSTAXH tstaxh;
		TSTPROD tstprod;
		CLRP clrp;
		MULAXH mulaxh;
		CMP cmp;
		CLR clr;
		NX nx;
		MOVNP movnp;
		NOT not;
		NEG neg;
		DEC dec;
		DECM decm;
		INC inc;
		INCM incm;
		ADDAXL addaxl;
		MOVP movp;
		MOV mov;
		MOVAX movax;
		MOVR movr;
		SUBP subp;
		SUB sub;
		SUBARN subarn;
		SUBAX subax;
		SUBR subr;
		ADDP addp;
		ADD add;
		ADDAX addax;
		ADDR addr;
		ORC orc;
		ANDC andc;
		ORR orr;
		ANDR andr;
		XORR xorr;
		XORC xorc;
		SRSH srsh;
		SRS srs;
		LRS lrs;
		MRR mrr;
		SRRN srrn;
		SRRI srri;
		SRRD srrd;
		SRR srr;
		LRRN lrrn;
		LRRI lrri;
		LRRD lrrd;
		LRR lrr;
		JMPR_CC jmpr_cc;
		CALLRCC callrcc;
		SI si;
		ASR asr;
		ASL asl;
		LSR lsr;
		LSL lsl;
		SBSET sbset;
		SBCLR sbclr;
		BLOOPI bloopi;
		LOOPI loopi;
		LRIS lris;
		CMPIS cmpis;
		ADDIS addis;
		ILRRN ilrrn;
		ILRRI ilrri;
		ILRRD ilrrd;
		ILRR ilrr;
		ANDF andf;
		ANDCF andcf;
		CMPI cmpi;
		ORI ori;
		ANDI andi;
		XORI xori;
		ADDI addi;
		LSRNRX lsrnrx;
		LSRNR lsrnr;
		ASRNRX asrnrx;
		ASRNR asrnr;
		LSRN lsrn;
		ASRN asrn;
		RTI_CC rti_cc;
		RET_CC ret_cc;
		CALL_CC call_cc;
		JMP_CC jmp_cc;
		IF_CC if_cc;
		SR sr;
		LR lr;
		LRI lri;
		BLOOP bloop;
		LOOP loop;
		HALT halt;
		ADDARN addarn;
		IAR iar;
		DAR dar;
		NOP nop;
    }
}

struct ExtensionInstruction {
    ExtensionOpcode opcode;

    union {
        EXT_LDAXNM ldaxnm;
		EXT_LDNM ldnm;
		EXT_LDAXM ldaxm;
		EXT_LDM ldm;
		EXT_LDAXN ldaxn;
		EXT_LDN ldn;
		EXT_LDAX ldax;
		EXT_LD ld;
		EXT_SLNM slnm;
		EXT_LSNM lsnm;
		EXT_SLM slm;
		EXT_LSM lsm;
		EXT_SLN sln;
		EXT_LSN lsn;
		EXT_SL sl;
		EXT_LS ls;
		EXT_LN ln;
		EXT_L l;
		EXT_SN sn;
		EXT_S s;
		EXT_MV mv;
		EXT_NR nr;
		EXT_IR ir;
		EXT_DR dr;
		EXT_NOP nop;
    }
}

struct DecodedInstruction {
    DspInstruction main;
    bool has_extension;
    ExtensionInstruction extension;
}

enum DspOpcode {
    NOP,
	DAR,
	IAR,
	ADDARN,
	HALT,
	LOOP,
	BLOOP,
	LRI,
	LR,
	SR,
	IF_CC,
	JMP_CC,
	CALL_CC,
	RET_CC,
	RTI_CC,
	ASRN,
	LSRN,
	ASRNR,
	ASRNRX,
	LSRNR,
	LSRNRX,
	ADDI,
	XORI,
	ANDI,
	ORI,
	CMPI,
	ANDCF,
	ANDF,
	ILRR,
	ILRRD,
	ILRRI,
	ILRRN,
	ADDIS,
	CMPIS,
	LRIS,
	LOOPI,
	BLOOPI,
	SBCLR,
	SBSET,
	LSL,
	LSR,
	ASL,
	ASR,
	SI,
	CALLRCC,
	JMPR_CC,
	LRR,
	LRRD,
	LRRI,
	LRRN,
	SRR,
	SRRD,
	SRRI,
	SRRN,
	MRR,
	LRS,
	SRS,
	SRSH,
	XORC,
	XORR,
	ANDR,
	ORR,
	ANDC,
	ORC,
	ADDR,
	ADDAX,
	ADD,
	ADDP,
	SUBR,
	SUBAX,
	SUBARN,
	SUB,
	SUBP,
	MOVR,
	MOVAX,
	MOV,
	MOVP,
	ADDAXL,
	INCM,
	INC,
	DECM,
	DEC,
	NEG,
	NOT,
	MOVNP,
	NX,
	CLR,
	CMP,
	MULAXH,
	CLRP,
	TSTPROD,
	TSTAXH,
	M2,
	M0,
	CLR15,
	SET15,
	SET16,
	SET40,
	MUL,
	ASR16,
	MULMVZ,
	MULAC,
	MULMV,
	MULX,
	ABS,
	TST,
	MULXMVZ,
	MULXAC,
	MULXMV,
	MULC,
	CMPAXH,
	MULCMVZ,
	MULCAC,
	MULCMV,
	MADDX,
	MSUBX,
	MADDC,
	MSUBC,
	LSL16,
	MADD,
	LSR16,
	MSUB,
	ADDPAXZ,
	CLRL,
	MOVPZ,
}

enum ExtensionOpcode {
    EXT_NOP,
	EXT_DR,
	EXT_IR,
	EXT_NR,
	EXT_MV,
	EXT_S,
	EXT_SN,
	EXT_L,
	EXT_LN,
	EXT_LS,
	EXT_SL,
	EXT_LSN,
	EXT_SLN,
	EXT_LSM,
	EXT_SLM,
	EXT_LSNM,
	EXT_SLNM,
	EXT_LD,
	EXT_LDAX,
	EXT_LDN,
	EXT_LDAXN,
	EXT_LDM,
	EXT_LDAXM,
	EXT_LDNM,
	EXT_LDAXNM,
}

struct NOP {
    
}

struct DAR {
    u16 a;
}

struct IAR {
    u16 a;
}

struct ADDARN {
    u16 s;
	u16 d;
}

struct HALT {
    
}

struct LOOP {
    u16 r;
}

struct BLOOP {
    u16 r;
	u16 a;
}

struct LRI {
    u16 r;
	u16 i;
}

struct LR {
    u16 r;
	u16 m;
}

struct SR {
    u16 r;
	u16 m;
}

struct IF_CC {
    u16 c;
}

struct JMP_CC {
    u16 c;
	u16 a;
}

struct CALL_CC {
    u16 c;
	u16 a;
}

struct RET_CC {
    u16 c;
}

struct RTI_CC {
    u16 c;
}

struct ASRN {
    
}

struct LSRN {
    
}

struct ASRNR {
    u16 d;
	u16 x;
}

struct ASRNRX {
    u16 s;
	u16 d;
	u16 x;
}

struct LSRNR {
    u16 d;
	u16 x;
}

struct LSRNRX {
    u16 s;
	u16 d;
	u16 x;
}

struct ADDI {
    u16 d;
	u16 i;
}

struct XORI {
    u16 r;
	u16 i;
}

struct ANDI {
    u16 r;
	u16 i;
}

struct ORI {
    u16 r;
	u16 i;
}

struct CMPI {
    u16 r;
	u16 i;
}

struct ANDCF {
    u16 r;
	u16 i;
}

struct ANDF {
    u16 r;
	u16 i;
}

struct ILRR {
    u16 r;
	u16 a;
}

struct ILRRD {
    u16 d;
	u16 s;
}

struct ILRRI {
    u16 d;
	u16 s;
}

struct ILRRN {
    u16 d;
	u16 s;
}

struct ADDIS {
    u16 d;
	u16 i;
}

struct CMPIS {
    u16 d;
	u16 i;
}

struct LRIS {
    u16 r;
	u16 i;
}

struct LOOPI {
    u16 i;
}

struct BLOOPI {
    u16 i;
	u16 a;
}

struct SBCLR {
    u16 i;
}

struct SBSET {
    u16 i;
}

struct LSL {
    u16 r;
	u16 s;
}

struct LSR {
    u16 r;
	u16 s;
}

struct ASL {
    u16 r;
	u16 s;
}

struct ASR {
    u16 r;
	u16 s;
}

struct SI {
    u16 i;
	u16 m;
}

struct CALLRCC {
    u16 r;
	u16 c;
}

struct JMPR_CC {
    u16 r;
	u16 c;
}

struct LRR {
    u16 a;
	u16 r;
}

struct LRRD {
    u16 a;
	u16 r;
}

struct LRRI {
    u16 a;
	u16 r;
}

struct LRRN {
    u16 a;
	u16 r;
}

struct SRR {
    u16 a;
	u16 r;
}

struct SRRD {
    u16 a;
	u16 r;
}

struct SRRI {
    u16 a;
	u16 r;
}

struct SRRN {
    u16 a;
	u16 r;
}

struct MRR {
    u16 d;
	u16 s;
}

struct LRS {
    u16 r;
	u16 m;
}

struct SRS {
    u16 r;
	u16 m;
}

struct SRSH {
    u16 s;
	u16 m;
}

struct XORC {
    u16 d;
	u16 x;
}

struct XORR {
    u16 s;
	u16 r;
	u16 x;
}

struct ANDR {
    u16 s;
	u16 r;
	u16 x;
}

struct ORR {
    u16 s;
	u16 r;
	u16 x;
}

struct ANDC {
    u16 r;
	u16 x;
}

struct ORC {
    u16 r;
	u16 x;
}

struct ADDR {
    u16 s;
	u16 d;
	u16 x;
}

struct ADDAX {
    u16 s;
	u16 d;
	u16 x;
}

struct ADD {
    u16 d;
	u16 x;
}

struct ADDP {
    u16 d;
	u16 x;
}

struct SUBR {
    u16 s;
	u16 d;
	u16 x;
}

struct SUBAX {
    u16 s;
	u16 d;
	u16 x;
}

struct SUBARN {
    u16 d;
}

struct SUB {
    u16 d;
	u16 x;
}

struct SUBP {
    u16 d;
	u16 x;
}

struct MOVR {
    u16 s;
	u16 d;
	u16 x;
}

struct MOVAX {
    u16 s;
	u16 d;
	u16 x;
}

struct MOV {
    u16 d;
	u16 x;
}

struct MOVP {
    u16 d;
	u16 x;
}

struct ADDAXL {
    u16 s;
	u16 d;
	u16 x;
}

struct INCM {
    u16 d;
	u16 x;
}

struct INC {
    u16 d;
	u16 x;
}

struct DECM {
    u16 d;
	u16 x;
}

struct DEC {
    u16 d;
	u16 x;
}

struct NEG {
    u16 d;
	u16 x;
}

struct NOT {
    u16 d;
	u16 x;
}

struct MOVNP {
    u16 d;
	u16 x;
}

struct NX {
    u16 y;
	u16 x;
}

struct CLR {
    u16 r;
	u16 x;
}

struct CMP {
    u16 x;
}

struct MULAXH {
    u16 x;
}

struct CLRP {
    u16 x;
}

struct TSTPROD {
    u16 x;
}

struct TSTAXH {
    u16 r;
	u16 x;
}

struct M2 {
    u16 x;
}

struct M0 {
    u16 x;
}

struct CLR15 {
    u16 x;
}

struct SET15 {
    u16 x;
}

struct SET16 {
    u16 x;
}

struct SET40 {
    u16 x;
}

struct MUL {
    u16 s;
	u16 x;
}

struct ASR16 {
    u16 r;
	u16 x;
}

struct MULMVZ {
    u16 s;
	u16 r;
	u16 x;
}

struct MULAC {
    u16 s;
	u16 r;
	u16 x;
}

struct MULMV {
    u16 s;
	u16 r;
	u16 x;
}

struct MULX {
    u16 s;
	u16 t;
	u16 x;
}

struct ABS {
    u16 d;
	u16 x;
}

struct TST {
    u16 r;
	u16 x;
}

struct MULXMVZ {
    u16 s;
	u16 t;
	u16 r;
	u16 x;
}

struct MULXAC {
    u16 s;
	u16 t;
	u16 r;
	u16 x;
}

struct MULXMV {
    u16 s;
	u16 t;
	u16 r;
	u16 x;
}

struct MULC {
    u16 s;
	u16 t;
	u16 x;
}

struct CMPAXH {
    u16 r;
	u16 s;
	u16 x;
}

struct MULCMVZ {
    u16 s;
	u16 t;
	u16 r;
	u16 x;
}

struct MULCAC {
    u16 s;
	u16 t;
	u16 r;
	u16 x;
}

struct MULCMV {
    u16 s;
	u16 t;
	u16 r;
	u16 x;
}

struct MADDX {
    u16 s;
	u16 t;
	u16 x;
}

struct MSUBX {
    u16 s;
	u16 t;
	u16 x;
}

struct MADDC {
    u16 s;
	u16 t;
	u16 x;
}

struct MSUBC {
    u16 s;
	u16 t;
	u16 x;
}

struct LSL16 {
    u16 r;
	u16 x;
}

struct MADD {
    u16 s;
	u16 x;
}

struct LSR16 {
    u16 r;
	u16 x;
}

struct MSUB {
    u16 s;
	u16 x;
}

struct ADDPAXZ {
    u16 s;
	u16 d;
	u16 x;
}

struct CLRL {
    u16 r;
	u16 x;
}

struct MOVPZ {
    u16 d;
	u16 x;
}

struct EXT_NOP {
    u16 x;
}

struct EXT_DR {
    u16 r;
}

struct EXT_IR {
    u16 r;
}

struct EXT_NR {
    u16 r;
}

struct EXT_MV {
    u16 d;
	u16 s;
}

struct EXT_S {
    u16 s;
	u16 d;
}

struct EXT_SN {
    u16 s;
	u16 d;
}

struct EXT_L {
    u16 d;
	u16 s;
}

struct EXT_LN {
    u16 d;
	u16 s;
}

struct EXT_LS {
    u16 d;
	u16 s;
}

struct EXT_SL {
    u16 d;
	u16 s;
}

struct EXT_LSN {
    u16 d;
	u16 s;
}

struct EXT_SLN {
    u16 d;
	u16 s;
}

struct EXT_LSM {
    u16 d;
	u16 s;
}

struct EXT_SLM {
    u16 d;
	u16 s;
}

struct EXT_LSNM {
    u16 d;
	u16 s;
}

struct EXT_SLNM {
    u16 d;
	u16 s;
}

struct EXT_LD {
    u16 d;
	u16 r;
	u16 s;
}

struct EXT_LDAX {
    u16 s;
	u16 r;
}

struct EXT_LDN {
    u16 d;
	u16 r;
	u16 s;
}

struct EXT_LDAXN {
    u16 s;
	u16 r;
}

struct EXT_LDM {
    u16 d;
	u16 r;
	u16 s;
}

struct EXT_LDAXM {
    u16 s;
	u16 r;
}

struct EXT_LDNM {
    u16 d;
	u16 r;
	u16 s;
}

struct EXT_LDAXNM {
    u16 s;
	u16 r;
}

ExtensionInstruction decode_extension(u16 instruction) {
	u8 ext_opcode = instruction & 0xFF;
	switch (ext_opcode) {
		case 0x00: return ExtensionInstruction(ExtensionOpcode.EXT_NOP, nop : EXT_NOP(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x01: return ExtensionInstruction(ExtensionOpcode.EXT_NOP, nop : EXT_NOP(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x02: return ExtensionInstruction(ExtensionOpcode.EXT_NOP, nop : EXT_NOP(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x03: return ExtensionInstruction(ExtensionOpcode.EXT_NOP, nop : EXT_NOP(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x04: return ExtensionInstruction(ExtensionOpcode.EXT_DR, dr : EXT_DR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x05: return ExtensionInstruction(ExtensionOpcode.EXT_DR, dr : EXT_DR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x06: return ExtensionInstruction(ExtensionOpcode.EXT_DR, dr : EXT_DR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x07: return ExtensionInstruction(ExtensionOpcode.EXT_DR, dr : EXT_DR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x08: return ExtensionInstruction(ExtensionOpcode.EXT_IR, ir : EXT_IR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x09: return ExtensionInstruction(ExtensionOpcode.EXT_IR, ir : EXT_IR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x0a: return ExtensionInstruction(ExtensionOpcode.EXT_IR, ir : EXT_IR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x0b: return ExtensionInstruction(ExtensionOpcode.EXT_IR, ir : EXT_IR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x0c: return ExtensionInstruction(ExtensionOpcode.EXT_NR, nr : EXT_NR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x0d: return ExtensionInstruction(ExtensionOpcode.EXT_NR, nr : EXT_NR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x0e: return ExtensionInstruction(ExtensionOpcode.EXT_NR, nr : EXT_NR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x0f: return ExtensionInstruction(ExtensionOpcode.EXT_NR, nr : EXT_NR(cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x10: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x11: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x12: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x13: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x14: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x15: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x16: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x17: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x18: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x19: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x1a: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x1b: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x1c: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x1d: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x1e: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x1f: return ExtensionInstruction(ExtensionOpcode.EXT_MV, mv : EXT_MV(cast(u16) (instruction & 0xFF).bits(2, 3), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x20: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x21: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x22: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x23: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x24: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x25: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x26: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x27: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x28: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x29: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x2a: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x2b: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x2c: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x2d: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x2e: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x2f: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x30: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x31: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x32: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x33: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x34: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x35: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x36: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x37: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x38: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x39: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x3a: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x3b: return ExtensionInstruction(ExtensionOpcode.EXT_S, s : EXT_S(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x3c: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x3d: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x3e: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x3f: return ExtensionInstruction(ExtensionOpcode.EXT_SN, sn : EXT_SN(cast(u16) (instruction & 0xFF).bits(3, 4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x40: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x41: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x42: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x43: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x44: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x45: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x46: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x47: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x48: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x49: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x4a: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x4b: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x4c: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x4d: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x4e: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x4f: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x50: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x51: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x52: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x53: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x54: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x55: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x56: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x57: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x58: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x59: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x5a: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x5b: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x5c: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x5d: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x5e: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x5f: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x60: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x61: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x62: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x63: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x64: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x65: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x66: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x67: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x68: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x69: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x6a: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x6b: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x6c: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x6d: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x6e: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x6f: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x70: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x71: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x72: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x73: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x74: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x75: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x76: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x77: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x78: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x79: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x7a: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x7b: return ExtensionInstruction(ExtensionOpcode.EXT_L, l : EXT_L(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x7c: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x7d: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x7e: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x7f: return ExtensionInstruction(ExtensionOpcode.EXT_LN, ln : EXT_LN(cast(u16) (instruction & 0xFF).bits(3, 5), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0x80: return ExtensionInstruction(ExtensionOpcode.EXT_LS, ls : EXT_LS(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x81: return ExtensionInstruction(ExtensionOpcode.EXT_LS, ls : EXT_LS(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x82: return ExtensionInstruction(ExtensionOpcode.EXT_SL, sl : EXT_SL(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x83: return ExtensionInstruction(ExtensionOpcode.EXT_SL, sl : EXT_SL(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x84: return ExtensionInstruction(ExtensionOpcode.EXT_LSN, lsn : EXT_LSN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x85: return ExtensionInstruction(ExtensionOpcode.EXT_LSN, lsn : EXT_LSN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x86: return ExtensionInstruction(ExtensionOpcode.EXT_SLN, sln : EXT_SLN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x87: return ExtensionInstruction(ExtensionOpcode.EXT_SLN, sln : EXT_SLN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x88: return ExtensionInstruction(ExtensionOpcode.EXT_LSM, lsm : EXT_LSM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x89: return ExtensionInstruction(ExtensionOpcode.EXT_LSM, lsm : EXT_LSM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x8a: return ExtensionInstruction(ExtensionOpcode.EXT_SLM, slm : EXT_SLM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x8b: return ExtensionInstruction(ExtensionOpcode.EXT_SLM, slm : EXT_SLM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x8c: return ExtensionInstruction(ExtensionOpcode.EXT_LSNM, lsnm : EXT_LSNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x8d: return ExtensionInstruction(ExtensionOpcode.EXT_LSNM, lsnm : EXT_LSNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x8e: return ExtensionInstruction(ExtensionOpcode.EXT_SLNM, slnm : EXT_SLNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x8f: return ExtensionInstruction(ExtensionOpcode.EXT_SLNM, slnm : EXT_SLNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x90: return ExtensionInstruction(ExtensionOpcode.EXT_LS, ls : EXT_LS(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x91: return ExtensionInstruction(ExtensionOpcode.EXT_LS, ls : EXT_LS(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x92: return ExtensionInstruction(ExtensionOpcode.EXT_SL, sl : EXT_SL(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x93: return ExtensionInstruction(ExtensionOpcode.EXT_SL, sl : EXT_SL(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x94: return ExtensionInstruction(ExtensionOpcode.EXT_LSN, lsn : EXT_LSN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x95: return ExtensionInstruction(ExtensionOpcode.EXT_LSN, lsn : EXT_LSN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x96: return ExtensionInstruction(ExtensionOpcode.EXT_SLN, sln : EXT_SLN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x97: return ExtensionInstruction(ExtensionOpcode.EXT_SLN, sln : EXT_SLN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x98: return ExtensionInstruction(ExtensionOpcode.EXT_LSM, lsm : EXT_LSM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x99: return ExtensionInstruction(ExtensionOpcode.EXT_LSM, lsm : EXT_LSM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x9a: return ExtensionInstruction(ExtensionOpcode.EXT_SLM, slm : EXT_SLM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x9b: return ExtensionInstruction(ExtensionOpcode.EXT_SLM, slm : EXT_SLM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x9c: return ExtensionInstruction(ExtensionOpcode.EXT_LSNM, lsnm : EXT_LSNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x9d: return ExtensionInstruction(ExtensionOpcode.EXT_LSNM, lsnm : EXT_LSNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x9e: return ExtensionInstruction(ExtensionOpcode.EXT_SLNM, slnm : EXT_SLNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0x9f: return ExtensionInstruction(ExtensionOpcode.EXT_SLNM, slnm : EXT_SLNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xa0: return ExtensionInstruction(ExtensionOpcode.EXT_LS, ls : EXT_LS(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xa1: return ExtensionInstruction(ExtensionOpcode.EXT_LS, ls : EXT_LS(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xa2: return ExtensionInstruction(ExtensionOpcode.EXT_SL, sl : EXT_SL(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xa3: return ExtensionInstruction(ExtensionOpcode.EXT_SL, sl : EXT_SL(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xa4: return ExtensionInstruction(ExtensionOpcode.EXT_LSN, lsn : EXT_LSN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xa5: return ExtensionInstruction(ExtensionOpcode.EXT_LSN, lsn : EXT_LSN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xa6: return ExtensionInstruction(ExtensionOpcode.EXT_SLN, sln : EXT_SLN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xa7: return ExtensionInstruction(ExtensionOpcode.EXT_SLN, sln : EXT_SLN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xa8: return ExtensionInstruction(ExtensionOpcode.EXT_LSM, lsm : EXT_LSM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xa9: return ExtensionInstruction(ExtensionOpcode.EXT_LSM, lsm : EXT_LSM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xaa: return ExtensionInstruction(ExtensionOpcode.EXT_SLM, slm : EXT_SLM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xab: return ExtensionInstruction(ExtensionOpcode.EXT_SLM, slm : EXT_SLM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xac: return ExtensionInstruction(ExtensionOpcode.EXT_LSNM, lsnm : EXT_LSNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xad: return ExtensionInstruction(ExtensionOpcode.EXT_LSNM, lsnm : EXT_LSNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xae: return ExtensionInstruction(ExtensionOpcode.EXT_SLNM, slnm : EXT_SLNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xaf: return ExtensionInstruction(ExtensionOpcode.EXT_SLNM, slnm : EXT_SLNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xb0: return ExtensionInstruction(ExtensionOpcode.EXT_LS, ls : EXT_LS(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xb1: return ExtensionInstruction(ExtensionOpcode.EXT_LS, ls : EXT_LS(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xb2: return ExtensionInstruction(ExtensionOpcode.EXT_SL, sl : EXT_SL(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xb3: return ExtensionInstruction(ExtensionOpcode.EXT_SL, sl : EXT_SL(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xb4: return ExtensionInstruction(ExtensionOpcode.EXT_LSN, lsn : EXT_LSN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xb5: return ExtensionInstruction(ExtensionOpcode.EXT_LSN, lsn : EXT_LSN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xb6: return ExtensionInstruction(ExtensionOpcode.EXT_SLN, sln : EXT_SLN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xb7: return ExtensionInstruction(ExtensionOpcode.EXT_SLN, sln : EXT_SLN(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xb8: return ExtensionInstruction(ExtensionOpcode.EXT_LSM, lsm : EXT_LSM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xb9: return ExtensionInstruction(ExtensionOpcode.EXT_LSM, lsm : EXT_LSM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xba: return ExtensionInstruction(ExtensionOpcode.EXT_SLM, slm : EXT_SLM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xbb: return ExtensionInstruction(ExtensionOpcode.EXT_SLM, slm : EXT_SLM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xbc: return ExtensionInstruction(ExtensionOpcode.EXT_LSNM, lsnm : EXT_LSNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xbd: return ExtensionInstruction(ExtensionOpcode.EXT_LSNM, lsnm : EXT_LSNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xbe: return ExtensionInstruction(ExtensionOpcode.EXT_SLNM, slnm : EXT_SLNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xbf: return ExtensionInstruction(ExtensionOpcode.EXT_SLNM, slnm : EXT_SLNM(cast(u16) (instruction & 0xFF).bits(4, 5), cast(u16) (instruction & 0xFF).bit(0)));
		case 0xc0: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xc1: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xc2: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xc3: return ExtensionInstruction(ExtensionOpcode.EXT_LDAX, ldax : EXT_LDAX(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xc4: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xc5: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xc6: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xc7: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXN, ldaxn : EXT_LDAXN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xc8: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xc9: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xca: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xcb: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXM, ldaxm : EXT_LDAXM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xcc: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xcd: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xce: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xcf: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXNM, ldaxnm : EXT_LDAXNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xd0: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xd1: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xd2: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xd3: return ExtensionInstruction(ExtensionOpcode.EXT_LDAX, ldax : EXT_LDAX(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xd4: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xd5: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xd6: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xd7: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXN, ldaxn : EXT_LDAXN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xd8: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xd9: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xda: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xdb: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXM, ldaxm : EXT_LDAXM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xdc: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xdd: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xde: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xdf: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXNM, ldaxnm : EXT_LDAXNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xe0: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xe1: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xe2: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xe3: return ExtensionInstruction(ExtensionOpcode.EXT_LDAX, ldax : EXT_LDAX(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xe4: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xe5: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xe6: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xe7: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXN, ldaxn : EXT_LDAXN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xe8: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xe9: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xea: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xeb: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXM, ldaxm : EXT_LDAXM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xec: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xed: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xee: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xef: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXNM, ldaxnm : EXT_LDAXNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xf0: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xf1: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xf2: return ExtensionInstruction(ExtensionOpcode.EXT_LD, ld : EXT_LD(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xf3: return ExtensionInstruction(ExtensionOpcode.EXT_LDAX, ldax : EXT_LDAX(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xf4: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xf5: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xf6: return ExtensionInstruction(ExtensionOpcode.EXT_LDN, ldn : EXT_LDN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xf7: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXN, ldaxn : EXT_LDAXN(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xf8: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xf9: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xfa: return ExtensionInstruction(ExtensionOpcode.EXT_LDM, ldm : EXT_LDM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xfb: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXM, ldaxm : EXT_LDAXM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		case 0xfc: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xfd: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xfe: return ExtensionInstruction(ExtensionOpcode.EXT_LDNM, ldnm : EXT_LDNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4), cast(u16) (instruction & 0xFF).bits(0, 1)));
		case 0xff: return ExtensionInstruction(ExtensionOpcode.EXT_LDAXNM, ldaxnm : EXT_LDAXNM(cast(u16) (instruction & 0xFF).bit(5), cast(u16) (instruction & 0xFF).bit(4)));
		default:
			log_dsp("Unknown extension opcode: 0x%02x", ext_opcode);
			return ExtensionInstruction(ExtensionOpcode.EXT_NOP, nop : EXT_NOP());
	}
}

DspInstruction decode_instruction(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x2000) >> 13) << 0;
	index |= ((instruction & 0x4000) >> 14) << 1;
	index |= ((instruction & 0x8000) >> 15) << 2;

	switch (index) {
		case 0: return generated_table_1(instruction, next_instruction);
		case 1: return generated_table_2(instruction, next_instruction);
		case 2: return generated_table_3(instruction, next_instruction);
		case 3: return generated_table_4(instruction, next_instruction);
		case 4: return generated_table_5(instruction, next_instruction);
		case 5: return generated_table_6(instruction, next_instruction);
		case 6: return generated_table_7(instruction, next_instruction);
		case 7: return generated_table_8(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_1(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x800) >> 11) << 0;
	index |= ((instruction & 0x1000) >> 12) << 1;

	switch (index) {
		case 0: return generated_table_9(instruction, next_instruction);
		case 1: return DspInstruction(DspOpcode.LRIS, 16, lris : LRIS(instruction.bits(8, 10), instruction.bits(0, 7)));
		case 2: return generated_table_10(instruction, next_instruction);
		case 3: return generated_table_11(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_9(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;
	index |= ((instruction & 0x400) >> 10) << 1;

	switch (index) {
		case 0: return generated_table_12(instruction, next_instruction);
		case 1: return generated_table_13(instruction, next_instruction);
		case 2: return DspInstruction(DspOpcode.ADDIS, 16, addis : ADDIS(instruction.bit(8), instruction.bits(0, 7)));
		case 3: return DspInstruction(DspOpcode.CMPIS, 16, cmpis : CMPIS(instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_12(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x20) >> 5) << 0;
	index |= ((instruction & 0x40) >> 6) << 1;
	index |= ((instruction & 0x80) >> 7) << 2;
	index |= ((instruction & 0x100) >> 8) << 3;

	switch (index) {
		case 0: return generated_table_14(instruction, next_instruction);
		case 1: return DspInstruction(DspOpcode.HALT, 16, halt : HALT());
		case 2: return DspInstruction(DspOpcode.LOOP, 16, loop : LOOP(instruction.bits(0, 4)));
		case 3: return DspInstruction(DspOpcode.BLOOP, 32, bloop : BLOOP(instruction.bits(0, 4), next_instruction));
		case 4: return DspInstruction(DspOpcode.LRI, 32, lri : LRI(instruction.bits(0, 4), next_instruction));
		case 6: return DspInstruction(DspOpcode.LR, 32, lr : LR(instruction.bits(0, 4), next_instruction));
		case 7: return DspInstruction(DspOpcode.SR, 32, sr : SR(instruction.bits(0, 4), next_instruction));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_14(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x10) >> 4) << 0;

	switch (index) {
		case 0: return generated_table_15(instruction, next_instruction);
		case 1: return DspInstruction(DspOpcode.ADDARN, 16, addarn : ADDARN(instruction.bits(2, 3), instruction.bits(0, 1)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_15(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x4) >> 2) << 0;
	index |= ((instruction & 0x8) >> 3) << 1;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
		case 1: return DspInstruction(DspOpcode.DAR, 16, dar : DAR(instruction.bits(0, 1)));
		case 2: return DspInstruction(DspOpcode.IAR, 16, iar : IAR(instruction.bits(0, 1)));
		case 3: return DspInstruction(DspOpcode.SUBARN, 16, subarn : SUBARN(instruction.bits(0, 1)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_13(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x10) >> 4) << 0;
	index |= ((instruction & 0x20) >> 5) << 1;
	index |= ((instruction & 0x40) >> 6) << 2;
	index |= ((instruction & 0x80) >> 7) << 3;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.ADDI, 32, addi : ADDI(instruction.bit(8), next_instruction));
		case 1: return generated_table_16(instruction, next_instruction);
		case 2: return DspInstruction(DspOpcode.XORI, 32, xori : XORI(instruction.bit(8), next_instruction));
		case 4: return DspInstruction(DspOpcode.ANDI, 32, andi : ANDI(instruction.bit(8), next_instruction));
		case 6: return DspInstruction(DspOpcode.ORI, 32, ori : ORI(instruction.bit(8), next_instruction));
		case 7: return DspInstruction(DspOpcode.IF_CC, 16, if_cc : IF_CC(instruction.bits(0, 3)));
		case 8: return DspInstruction(DspOpcode.CMPI, 32, cmpi : CMPI(instruction.bit(8), next_instruction));
		case 9: return DspInstruction(DspOpcode.JMP_CC, 32, jmp_cc : JMP_CC(instruction.bits(0, 3), next_instruction));
		case 10: return DspInstruction(DspOpcode.ANDF, 32, andf : ANDF(instruction.bit(8), next_instruction));
		case 11: return DspInstruction(DspOpcode.CALL_CC, 32, call_cc : CALL_CC(instruction.bits(0, 3), next_instruction));
		case 12: return generated_table_17(instruction, next_instruction);
		case 13: return DspInstruction(DspOpcode.RET_CC, 16, ret_cc : RET_CC(instruction.bits(0, 3)));
		case 15: return DspInstruction(DspOpcode.RTI_CC, 16, rti_cc : RTI_CC(instruction.bits(0, 3)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_16(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x4) >> 2) << 0;
	index |= ((instruction & 0x8) >> 3) << 1;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.ILRR, 16, ilrr : ILRR(instruction.bit(8), instruction.bits(0, 1)));
		case 1: return DspInstruction(DspOpcode.ILRRD, 16, ilrrd : ILRRD(instruction.bit(8), instruction.bits(0, 1)));
		case 2: return DspInstruction(DspOpcode.ILRRI, 16, ilrri : ILRRI(instruction.bit(8), instruction.bits(0, 1)));
		case 3: return DspInstruction(DspOpcode.ILRRN, 16, ilrrn : ILRRN(instruction.bit(8), instruction.bits(0, 1)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_17(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x1) >> 0) << 0;
	index |= ((instruction & 0x2) >> 1) << 1;
	index |= ((instruction & 0x4) >> 2) << 2;
	index |= ((instruction & 0x8) >> 3) << 3;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.ANDCF, 32, andcf : ANDCF(instruction.bit(8), next_instruction));
		case 10: return DspInstruction(DspOpcode.LSRN, 16, lsrn : LSRN());
		case 11: return DspInstruction(DspOpcode.ASRN, 16, asrn : ASRN());
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_10(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;
	index |= ((instruction & 0x400) >> 10) << 1;

	switch (index) {
		case 0: return generated_table_18(instruction, next_instruction);
		case 1: return generated_table_19(instruction, next_instruction);
		case 2: return generated_table_20(instruction, next_instruction);
		case 3: return generated_table_21(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_18(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x100) >> 8) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.LOOPI, 16, loopi : LOOPI(instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.BLOOPI, 32, bloopi : BLOOPI(instruction.bits(0, 7), next_instruction));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_19(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x8) >> 3) << 0;
	index |= ((instruction & 0x10) >> 4) << 1;
	index |= ((instruction & 0x20) >> 5) << 2;
	index |= ((instruction & 0x40) >> 6) << 3;
	index |= ((instruction & 0x80) >> 7) << 4;
	index |= ((instruction & 0x100) >> 8) << 5;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.SBCLR, 16, sbclr : SBCLR(instruction.bits(0, 2)));
		case 32: return DspInstruction(DspOpcode.SBSET, 16, sbset : SBSET(instruction.bits(0, 2)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_20(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x40) >> 6) << 0;
	index |= ((instruction & 0x80) >> 7) << 1;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.LSL, 16, lsl : LSL(instruction.bit(8), instruction.bits(0, 5)));
		case 1: return DspInstruction(DspOpcode.LSR, 16, lsr : LSR(instruction.bit(8), instruction.bits(0, 5)));
		case 2: return DspInstruction(DspOpcode.ASL, 16, asl : ASL(instruction.bit(8), instruction.bits(0, 5)));
		case 3: return DspInstruction(DspOpcode.ASR, 16, asr : ASR(instruction.bit(8), instruction.bits(0, 5)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_21(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x100) >> 8) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.SI, 32, si : SI(instruction.bits(0, 7), next_instruction));
		case 1: return generated_table_22(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_22(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x10) >> 4) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.JMPR_CC, 16, jmpr_cc : JMPR_CC(instruction.bits(5, 7), instruction.bits(0, 3)));
		case 1: return DspInstruction(DspOpcode.CALLRCC, 16, callrcc : CALLRCC(instruction.bits(5, 7), instruction.bits(0, 3)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_11(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x400) >> 10) << 0;

	switch (index) {
		case 0: return generated_table_23(instruction, next_instruction);
		case 1: return DspInstruction(DspOpcode.MRR, 16, mrr : MRR(instruction.bits(5, 9), instruction.bits(0, 4)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_23(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x80) >> 7) << 0;
	index |= ((instruction & 0x100) >> 8) << 1;
	index |= ((instruction & 0x200) >> 9) << 2;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.LRR, 16, lrr : LRR(instruction.bits(5, 6), instruction.bits(0, 4)));
		case 1: return DspInstruction(DspOpcode.LRRD, 16, lrrd : LRRD(instruction.bits(5, 6), instruction.bits(0, 4)));
		case 2: return DspInstruction(DspOpcode.LRRI, 16, lrri : LRRI(instruction.bits(5, 6), instruction.bits(0, 4)));
		case 3: return DspInstruction(DspOpcode.LRRN, 16, lrrn : LRRN(instruction.bits(5, 6), instruction.bits(0, 4)));
		case 4: return DspInstruction(DspOpcode.SRR, 16, srr : SRR(instruction.bits(5, 6), instruction.bits(0, 4)));
		case 5: return DspInstruction(DspOpcode.SRRD, 16, srrd : SRRD(instruction.bits(5, 6), instruction.bits(0, 4)));
		case 6: return DspInstruction(DspOpcode.SRRI, 16, srri : SRRI(instruction.bits(5, 6), instruction.bits(0, 4)));
		case 7: return DspInstruction(DspOpcode.SRRN, 16, srrn : SRRN(instruction.bits(5, 6), instruction.bits(0, 4)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_2(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x800) >> 11) << 0;
	index |= ((instruction & 0x1000) >> 12) << 1;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.LRS, 16, lrs : LRS(instruction.bits(8, 10), instruction.bits(0, 7)));
		case 1: return generated_table_24(instruction, next_instruction);
		case 2: return generated_table_25(instruction, next_instruction);
		case 3: return generated_table_26(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_24(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x400) >> 10) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.SRSH, 16, srsh : SRSH(instruction.bit(8), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.SRS, 16, srs : SRS(instruction.bits(8, 9), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_25(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x80) >> 7) << 0;
	index |= ((instruction & 0x400) >> 10) << 1;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.XORR, 16, xorr : XORR(instruction.bit(9), instruction.bit(8), instruction.bits(0, 6)));
		case 1: return generated_table_27(instruction, next_instruction);
		case 2: return DspInstruction(DspOpcode.ANDR, 16, andr : ANDR(instruction.bit(9), instruction.bit(8), instruction.bits(0, 6)));
		case 3: return DspInstruction(DspOpcode.LSRNRX, 16, lsrnrx : LSRNRX(instruction.bit(9), instruction.bit(8), instruction.bits(0, 6)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_27(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.XORC, 16, xorc : XORC(instruction.bit(8), instruction.bits(0, 6)));
		case 1: return DspInstruction(DspOpcode.NOT, 16, not : NOT(instruction.bit(8), instruction.bits(0, 6)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_26(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x80) >> 7) << 0;
	index |= ((instruction & 0x400) >> 10) << 1;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.ORR, 16, orr : ORR(instruction.bit(9), instruction.bit(8), instruction.bits(0, 6)));
		case 1: return DspInstruction(DspOpcode.ASRNRX, 16, asrnrx : ASRNRX(instruction.bit(9), instruction.bit(8), instruction.bits(0, 6)));
		case 2: return generated_table_28(instruction, next_instruction);
		case 3: return generated_table_29(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_28(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.ANDC, 16, andc : ANDC(instruction.bit(8), instruction.bits(0, 6)));
		case 1: return DspInstruction(DspOpcode.ORC, 16, orc : ORC(instruction.bit(8), instruction.bits(0, 6)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_29(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.LSRNR, 16, lsrnr : LSRNR(instruction.bit(8), instruction.bits(0, 6)));
		case 1: return DspInstruction(DspOpcode.ASRNR, 16, asrnr : ASRNR(instruction.bit(8), instruction.bits(0, 6)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_3(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x800) >> 11) << 0;
	index |= ((instruction & 0x1000) >> 12) << 1;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.ADDR, 16, addr : ADDR(instruction.bits(9, 10), instruction.bit(8), instruction.bits(0, 7)));
		case 1: return generated_table_30(instruction, next_instruction);
		case 2: return DspInstruction(DspOpcode.SUBR, 16, subr : SUBR(instruction.bits(9, 10), instruction.bit(8), instruction.bits(0, 7)));
		case 3: return generated_table_31(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_30(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x400) >> 10) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.ADDAX, 16, addax : ADDAX(instruction.bit(9), instruction.bit(8), instruction.bits(0, 7)));
		case 1: return generated_table_32(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_32(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.ADD, 16, add : ADD(instruction.bit(8), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.ADDP, 16, addp : ADDP(instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_31(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x400) >> 10) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.SUBAX, 16, subax : SUBAX(instruction.bit(9), instruction.bit(8), instruction.bits(0, 7)));
		case 1: return generated_table_33(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_33(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.SUB, 16, sub : SUB(instruction.bit(8), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.SUBP, 16, subp : SUBP(instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_4(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x800) >> 11) << 0;
	index |= ((instruction & 0x1000) >> 12) << 1;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.MOVR, 16, movr : MOVR(instruction.bits(9, 10), instruction.bit(8), instruction.bits(0, 7)));
		case 1: return generated_table_34(instruction, next_instruction);
		case 2: return generated_table_35(instruction, next_instruction);
		case 3: return generated_table_36(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_34(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x400) >> 10) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.MOVAX, 16, movax : MOVAX(instruction.bit(9), instruction.bit(8), instruction.bits(0, 7)));
		case 1: return generated_table_37(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_37(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.MOV, 16, mov : MOV(instruction.bit(8), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.MOVP, 16, movp : MOVP(instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_35(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x400) >> 10) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.ADDAXL, 16, addaxl : ADDAXL(instruction.bit(9), instruction.bit(8), instruction.bits(0, 7)));
		case 1: return generated_table_38(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_38(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.INCM, 16, incm : INCM(instruction.bit(8), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.INC, 16, inc : INC(instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_36(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;
	index |= ((instruction & 0x400) >> 10) << 1;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.DECM, 16, decm : DECM(instruction.bit(8), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.DEC, 16, dec : DEC(instruction.bit(8), instruction.bits(0, 7)));
		case 2: return DspInstruction(DspOpcode.NEG, 16, neg : NEG(instruction.bit(8), instruction.bits(0, 7)));
		case 3: return DspInstruction(DspOpcode.MOVNP, 16, movnp : MOVNP(instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_5(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;
	index |= ((instruction & 0x400) >> 10) << 1;
	index |= ((instruction & 0x1000) >> 12) << 2;

	switch (index) {
		case 0: return generated_table_39(instruction, next_instruction);
		case 1: return generated_table_40(instruction, next_instruction);
		case 2: return generated_table_41(instruction, next_instruction);
		case 3: return generated_table_42(instruction, next_instruction);
		case 4: return generated_table_43(instruction, next_instruction);
		case 5: return DspInstruction(DspOpcode.MULMVZ, 16, mulmvz : MULMVZ(instruction.bit(11), instruction.bit(8), instruction.bits(0, 7)));
		case 6: return DspInstruction(DspOpcode.MULAC, 16, mulac : MULAC(instruction.bit(11), instruction.bit(8), instruction.bits(0, 7)));
		case 7: return DspInstruction(DspOpcode.MULMV, 16, mulmv : MULMV(instruction.bit(11), instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_39(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x100) >> 8) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.NX, 16, nx : NX(instruction.bit(11), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.CLR, 16, clr : CLR(instruction.bit(11), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_40(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x100) >> 8) << 0;
	index |= ((instruction & 0x800) >> 11) << 1;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.CMP, 16, cmp : CMP(instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.MULAXH, 16, mulaxh : MULAXH(instruction.bits(0, 7)));
		case 2: return DspInstruction(DspOpcode.M2, 16, m2 : M2(instruction.bits(0, 7)));
		case 3: return DspInstruction(DspOpcode.M0, 16, m0 : M0(instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_41(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x100) >> 8) << 0;
	index |= ((instruction & 0x800) >> 11) << 1;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.CLRP, 16, clrp : CLRP(instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.TSTPROD, 16, tstprod : TSTPROD(instruction.bits(0, 7)));
		case 2: return DspInstruction(DspOpcode.CLR15, 16, clr15 : CLR15(instruction.bits(0, 7)));
		case 3: return DspInstruction(DspOpcode.SET15, 16, set15 : SET15(instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_42(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x800) >> 11) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.TSTAXH, 16, tstaxh : TSTAXH(instruction.bit(8), instruction.bits(0, 7)));
		case 1: return generated_table_44(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_44(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x100) >> 8) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.SET16, 16, set16 : SET16(instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.SET40, 16, set40 : SET40(instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_43(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x100) >> 8) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.MUL, 16, mul : MUL(instruction.bit(11), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.ASR16, 16, asr16 : ASR16(instruction.bit(11), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_6(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;
	index |= ((instruction & 0x400) >> 10) << 1;

	switch (index) {
		case 0: return generated_table_45(instruction, next_instruction);
		case 1: return DspInstruction(DspOpcode.MULXMVZ, 16, mulxmvz : MULXMVZ(instruction.bit(12), instruction.bit(11), instruction.bit(8), instruction.bits(0, 7)));
		case 2: return DspInstruction(DspOpcode.MULXAC, 16, mulxac : MULXAC(instruction.bit(12), instruction.bit(11), instruction.bit(8), instruction.bits(0, 7)));
		case 3: return DspInstruction(DspOpcode.MULXMV, 16, mulxmv : MULXMV(instruction.bit(12), instruction.bit(11), instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_45(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x100) >> 8) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.MULX, 16, mulx : MULX(instruction.bit(12), instruction.bit(11), instruction.bits(0, 7)));
		case 1: return generated_table_46(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_46(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x1000) >> 12) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.ABS, 16, abs : ABS(instruction.bit(11), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.TST, 16, tst : TST(instruction.bit(11), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_7(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;
	index |= ((instruction & 0x400) >> 10) << 1;

	switch (index) {
		case 0: return generated_table_47(instruction, next_instruction);
		case 1: return DspInstruction(DspOpcode.MULCMVZ, 16, mulcmvz : MULCMVZ(instruction.bit(12), instruction.bit(11), instruction.bit(8), instruction.bits(0, 7)));
		case 2: return DspInstruction(DspOpcode.MULCAC, 16, mulcac : MULCAC(instruction.bit(12), instruction.bit(11), instruction.bit(8), instruction.bits(0, 7)));
		case 3: return DspInstruction(DspOpcode.MULCMV, 16, mulcmv : MULCMV(instruction.bit(12), instruction.bit(11), instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_47(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x100) >> 8) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.MULC, 16, mulc : MULC(instruction.bit(12), instruction.bit(11), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.CMPAXH, 16, cmpaxh : CMPAXH(instruction.bit(12), instruction.bit(11), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_8(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x400) >> 10) << 0;
	index |= ((instruction & 0x800) >> 11) << 1;
	index |= ((instruction & 0x1000) >> 12) << 2;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.MADDX, 16, maddx : MADDX(instruction.bit(9), instruction.bit(8), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.MSUBX, 16, msubx : MSUBX(instruction.bit(9), instruction.bit(8), instruction.bits(0, 7)));
		case 2: return DspInstruction(DspOpcode.MADDC, 16, maddc : MADDC(instruction.bit(9), instruction.bit(8), instruction.bits(0, 7)));
		case 3: return DspInstruction(DspOpcode.MSUBC, 16, msubc : MSUBC(instruction.bit(9), instruction.bit(8), instruction.bits(0, 7)));
		case 4: return generated_table_48(instruction, next_instruction);
		case 5: return generated_table_49(instruction, next_instruction);
		case 6: return DspInstruction(DspOpcode.ADDPAXZ, 16, addpaxz : ADDPAXZ(instruction.bit(9), instruction.bit(8), instruction.bits(0, 7)));
		case 7: return generated_table_50(instruction, next_instruction);
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_48(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.LSL16, 16, lsl16 : LSL16(instruction.bit(8), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.MADD, 16, madd : MADD(instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_49(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.LSR16, 16, lsr16 : LSR16(instruction.bit(8), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.MSUB, 16, msub : MSUB(instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DspInstruction generated_table_50(u16 instruction, u16 next_instruction) {
	u16 index = 0;
	index |= ((instruction & 0x200) >> 9) << 0;

	switch (index) {
		case 0: return DspInstruction(DspOpcode.CLRL, 16, clrl : CLRL(instruction.bit(8), instruction.bits(0, 7)));
		case 1: return DspInstruction(DspOpcode.MOVPZ, 16, movpz : MOVPZ(instruction.bit(8), instruction.bits(0, 7)));
		default:
			log_dsp("Unknown instruction opcode: 0x%04x (index: %d)", instruction, index);
			return DspInstruction(DspOpcode.NOP, 16, nop : NOP());
	}
}

DecodedInstruction decode_instruction_with_extension(u16 instruction, u16 next_instruction) {
	DspInstruction main_inst = decode_instruction(instruction, next_instruction);
	bool has_ext = false;
	ExtensionInstruction ext_inst;

	// Check if main instruction can have extension (first nybble >= 4)
	if ((instruction >> 12) >= 4) {
		// Extension is always present if instruction can have one
		ext_inst = decode_extension(instruction);
		has_ext = true;
	}

	return DecodedInstruction(main_inst, has_ext, ext_inst);
}

